### ISSUE TITLE
please add sub policies & Guidelines Document 

### ISSUE THREAD

**Issue by anivar** [captn3m0/kerala-it-policy#1]
Kerala State Information Technology Policy 2017- Sub Policies and Guidelines-  Draft (English) 
https://www.kerala.gov.in/documents/10180/e63c8e02-4d9a-4e55-8677-93506c11e450

Malayalam Version contains many Translation mistakes such as Free Software translated as Gratis software

**Comment by captn3m0** [comment]
I don't know Malayalam so didn't check those, but the sub-policies document (english) is really large at 50 pages.

Checking if I can do it via a automated approach so I can do the formatting faster.
